import './styles/globals.scss'
import React from "react";


export const metadata = {
    title: 'Prozheiko',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    )
}
